CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Memoria para pantalla de color 240x240 (a ajustar si el build se queja)
CONFIG_LV_Z_VDB_SIZE=16
CONFIG_LV_Z_MEM_POOL_SIZE=32768