# Pantalla OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_I2C=y

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# LVGL
CONFIG_LVGL=y

# Widgets
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Logs
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y

CONFIG_INIT_STACKS=y